### ISSUE TITLE
请求允许样式覆盖

### ISSUE THREAD

**Issue by zpChiu** [lspriv/wx-calendar#108]
组件开启了样式隔离，无法对组件进行样式覆盖。有时候想调整一下组件高度或者节日被选中的颜色（都没有开放变量样式），都无法实现。大佬能新增一下样式覆盖的class吗

**Comment by lspriv** [comment]
好，我出个插件

**Comment by lspriv** [comment]
> 好，我出个插件

说实话，之所以没放开样式隔离，是要控制高度，还有你需要哪些覆盖的样式？

**Comment by zpChiu** [comment]
> > 好，我出个插件
> 
> 说实话，之所以没放开样式隔离，是要控制高度，还有你需要哪些覆盖的样式？

你好，需要对类名.wcc的样式覆盖。
我在使用的过程中，发现因样式隔离所产生的部分不便。
比如被选中的字体颜色是无法调整，日期右上方的dot，上下左右的距离上也是无法微调，以及组件的高度是固定的（该组件在部分老旧机型上，采用组件铺开的方式，高度大概占到60%，我想适配一下部分机型的高度比，需要微调组件高度）
希望Owner可以开放组件的样式覆盖

**Comment by lspriv** [comment]
移除包中index.json中的styleIsolation即可
![截屏2024-11-30 12 01 18](https://github.com/user-attachments/assets/9f4475aa-b943-42ab-bdc5-3f416807d006)
