### ISSUE TITLE
app.json: 在项目根目录未找到 app.json 

### ISSUE THREAD

**Issue by zjw1991** [lspriv/wx-calendar#116]
**描述**

**复现（选填，没有则这段删掉）**

**预期行为（选填，没有则这段删掉）**

**截图（选填，没有则这段删掉）**

**环境**
<table>
    <tr>
        <th>客户端类型</th>
        <th>微信版本</th>
        <th>基础库版本</th>
    </tr>
    <tr>
        <td>ios/android/windows/mac/devtools</td>
        <td>0.0.0</td>
        <td>0.0.0</td>
    </tr>
</table>

**Comment by lspriv** [comment]
请看 [使用教程](https://github.com/lspriv/wx-calendar?tab=readme-ov-file#%E4%BD%BF%E7%94%A8)
