### ISSUE TITLE
请问可以设置成周一是一周的起始日期吗，现在是周日是一周的开始

### ISSUE THREAD

**Issue by Kris696** [lspriv/wx-calendar#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lspriv** [comment]
现在的话还不行，这两天重新设计会加上这个设计

**Comment by Kris696** [comment]
感恩大佬！！！如果完成了烦请告知一声，能给我带来很大帮助~~~~

**Comment by Kris696** [comment]
感恩大佬！！！如果完成了烦请告知一声，能给我带来很大帮助~~~~

**Comment by lspriv** [comment]
2.0已提交，可以设置周开始星期了
