### ISSUE TITLE
左右滑动日历主体的时候，最上面的年份和月份不会跟着变化

### ISSUE THREAD

**Issue by Pooooooocky** [lspriv/wx-calendar#141]
机型：荣耀100pro
Bug：左右滑动📅日历主体的时候，最上面的年份和月份不会跟着变化

iPhone机型是正常的

https://github.com/user-attachments/assets/a3a5dbc5-e1b6-48a9-9954-28d6f7b4d635

**Comment by lspriv** [comment]
已调整发包，@lspriv/wx-calendar@1.7.3-alpha.1
