### ISSUE TITLE
真机预览时点击周视图,滑动手势不起作用,月视图上面三行点击无反应

### ISSUE THREAD

**Issue by lxz666** [lspriv/wx-calendar#142]
**描述**

 Component "miniprogram_npm/@lspriv/wx-calendar/index" does not have a method "function (nv_e,nv_t){var nv_a = nv_e.nv_mark;nv_t = nv_t.nv_getState();nv_a.nv_gesture && (nv_t.nv_y = nv_e.nv_changedTouches[(0)].nv_pageY , nv_t.nv_deg = 0 , nv_t.nv_lastTime = nv_e.nv_timeStamp , nv_t.nv_lastX = nv_e.nv_changedTouches[(0)].nv_pageX , nv_t.nv_lastY = nv_t.nv_y , nv_t.nv_check = 0 , "week" === nv_a.nv_view && (nv_t.nv_currentHeight = nv_a.nv_min) , "month" === nv_a.nv_view && (nv_t.nv_currentHeight = nv_a.nv_main) , "schedule" === nv_a.nv_view) && (nv_t.nv_currentHeight = nv_a.nv_max)}" to handle event "touchstart".

手机系统是iOS,模拟器上正常

**Comment by lspriv** [comment]
试了，正常，touchstart本身没有问题

**Comment by lxz666** [comment]
前些天还好,今天突然发现左右切换日期没变,有些日期点击没反应,还有就是警告有些方法找不到

https://github.com/user-attachments/assets/02316277-79ca-45a5-84e0-2cf9c9048d53
