### ISSUE TITLE
真机出现bug

### ISSUE THREAD

**Issue by xahy123** [lspriv/wx-calendar#144]
编辑器上正常，真机报错
<img width="474" alt="image" src="https://github.com/user-attachments/assets/5bb39121-905e-4e5a-9939-fb4a4b6917b8">

真机出现异常
<img width="792" alt="image" src="https://github.com/user-attachments/assets/6b793115-82d6-4126-b474-9097760a4048">

使用的taro，组件版本为1.7.3-alpha.6

**Comment by xahy123** [comment]
解决了，这个问题是微信开发者工具问题。但是在真机上看有个新问题

![image](https://github.com/user-attachments/assets/2d8555fa-7243-49b3-b727-2fcfaa675992)

**Comment by lspriv** [comment]
这个我注意到了，已经有人提了，自从小程序版本库升到最近几个版本后开始出现了这种情况，疑似wxs事件绑定的问题

**Comment by lspriv** [comment]
> 解决了，这个问题是微信开发者工具问题。但是在真机上看有个新问题
> 
> ![image](https://private-user-images.githubusercontent.com/43662455/355539589-2d8555fa-7243-49b3-b727-2fcfaa675992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzg0NTEsIm5iZiI6MTcyMzAzODE1MSwicGF0aCI6Ii80MzY2MjQ1NS8zNTU1Mzk1ODktMmQ4NTU1ZmEtNzI0My00OWIzLWI3MjctMmZjZmFhNjc1OTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDEzNDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NjIwZmFiMzNmNWIwMTMyZjUxZjBmZThjMDQ4YWIxNzk1YjlhNDNmNWM4M2ZlYzBjNTg0MGI5ODllZmI5YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QWHuwPy3y3Lg6rYygTqOnHYDDgDG_l6BvwhsjSR1P64)

之前事件绑定的方式有调整，官方的解释如下

![image](https://github.com/user-attachments/assets/830d2723-c8fb-45e1-b9c4-a3eadf88c3f6)

新包 `@lspriv/wx-calendar@1.7.3-alpha.7` 已调整解决
