### ISSUE TITLE
月视图切换周视图后日期消失

### ISSUE THREAD

**Issue by waynecraig** [lspriv/wx-calendar#147]
**描述**
发现问题的版本是：1.7.3-alpha.7

当一个月有六周时，在月视图下，选择当前日期的下一周的随便一天，然后切换到周视图，整个周视图的日期部分会消灭，用手去点一下那片区域，日期会重新显示。

**复现**
1. 初始化日期组件，全部用默认参数，显示一个月视图。
2. 点击月份，选择切换到一个有六周的月份，比如2024年6月。
3. 观察此时的日期是哪一天，然后选择它下一周的一天，比如我刚切换到2024年6月时，当前日期是2号，就可以点击9号。
4. 然后点击右上角的月/周切换按钮，就会看到，周视图下只有日一二三四五六，下面原本应该有的一行日期全是空白。
5. 此时如果点击一下那片空白区域，日期又会显示出来。

**预期行为**
切换到周视图，日期部分应该正常显示，不应该是空白。

**截图**
<img width="318" alt="Screenshot 2024-09-02 at 2 11 55 PM" src="https://github.com/user-attachments/assets/c8051ea7-e849-424a-840b-ebbf35e88a4f">

**环境**
<table>
    <tr>
        <th>客户端类型</th>
        <th>微信版本</th>
        <th>基础库版本</th>
    </tr>
    <tr>
        <td>ios/android/devtools</td>
        <td>8.0.50</td>
        <td>2.29.2</td>
    </tr>
</table>

**初步调试得到信息**
1. 在开放工具可以看到，会消失的周都带有一个 wc__panel-week--next 类。
2. 查看代码记录，应该是这一次 commit 引入的：https://github.com/lspriv/wx-calendar/commit/bf6cf99d080dea7239db7a7c705f94f265fd706c

**Comment by lspriv** [comment]
已修复，@lspriv/wx-calendar@1.7.3-alpha.8
