### ISSUE TITLE
农历1991年及之前的 6月数据对不上

### ISSUE THREAD

**Issue by sekaiai** [lspriv/wx-calendar#148]
**描述**
日历 | windows日历
--- | ---
 ![农历](https://github.com/user-attachments/assets/186366ce-46da-478d-a9f4-15551a24acc3) | ![windows日历](https://github.com/user-attachments/assets/c871567d-7bec-4698-a4ae-7216f301f4a7)

**Comment by lspriv** [comment]
已修复，包@lspriv/wx-calendar@1.7.3-alpha.9
