### ISSUE TITLE
bug提交

### ISSUE THREAD

**Issue by hjjjjhd** [lspriv/wx-calendar#27]
执行从月到周的视图切换时bug，例：
当前日期2021-11-22(月视图显示2021-10-31——2021-12-04)，从月视图选择2021-11-16后切换为周视图(周视图显示2021-11-14——2021-11-20)，**向后滑动周直接会跳转到2021-11-28(周视图显示2021-11-28——2021-12-04)**

个人调整：调整时发现在执行bindviewchange时，visual值没发生变化

**Comment by lspriv** [comment]
嗯嗯，这个很早注意到了，一直没抽出手来改，应该是周始日未更改的原因，随后改正



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月22日(周一) 下午3:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lspriv/wx-calendar] bug提交 (Issue #27)




 
执行从月到周的视图切换时bug，例：
 当前日期2021-11-22(月视图显示2021-10-31——2021-12-04)，从月视图选择2021-11-16后切换为周视图(周视图显示2021-11-14——2021-11-20)，向后滑动周直接会跳转到2021-11-28(周视图显示2021-11-28——2021-12-04)
 
个人调整：调整时发现在执行bindviewchange时，visual值没发生变化

**Comment by hjjjjhd** [comment]
大佬牛逼
