### ISSUE TITLE
连续快速向右滑动三次，触发了一次calendarSwiperEnd,但是顶部的年月日和间隔时间值显示错误

### ISSUE THREAD

**Issue by hanya-0323** [lspriv/wx-calendar#29]

**Comment by DYkk** [comment]
我这也发现了这个问题

**Comment by lspriv** [comment]
很早发现了

**Comment by DYkk** [comment]
> 很早发现了

这个问题解决没，大佬？

**Comment by lspriv** [comment]
> > 很早发现了
> 
> 这个问题解决没，大佬？

我还在想怎么设计，是防止快速滑动还是预计算快速滑动后与当前的差值，两种设计都有问题，还没确定哪一种影响更小，日历更新肯定是要放在swiper组件的bindanimationfinish事件里的，这是保证流畅滑动的关键，这也是连续快速滑动只触发了一次calendarSwiperEnd的原因

**Comment by JTXYH** [comment]
> 

只需要把bindanimationfinish事件改成bindchange事件就好了

**Comment by hanya-0323** [comment]
> > 
> 
> 只需要把bindanimationfinish事件改成bindchange事件就好了

我尝试了一下，不太行，会有其他问题产生

**Comment by JTXYH** [comment]
> > > 
> > 
> > 
> > 只需要把bindanimationfinish事件改成bindchange事件就好了
> 
> 我尝试了一下，不太行，会有其他问题产生

>> 我自己的小程序目前改成这样了  好像还没啥问题

**Comment by JTXYH** [comment]
> > > 
> > 
> > 
> > 只需要把bindanimationfinish事件改成bindchange事件就好了
> 
> 我尝试了一下，不太行，会有其他问题产生

有什么问题吗？我自己的小程序改成这样好像没啥问题

**Comment by lspriv** [comment]
已解决，分支develop

**Comment by lspriv** [comment]
已解决
