### ISSUE TITLE
关于使用的问题

### ISSUE THREAD

**Issue by drepig** [lspriv/wx-calendar#32]
是必须把所有文件夹都拷贝到我自己的项目目录下使用，然后组件只选用dist/wx-calendar使用吗？

我一开始只拷贝了dist/wx-calendar然后发现不能使用，绕了一圈试了下别人的日历，回过头来感觉还是想用你的，然后才把所有的都拷贝过来了才能成功使用。

感觉使用教程可以写的稍微更加详细一些，小白有点不懂。

另外就是，为什么dist/wx-calendar底下的代码都是直接一行的啊，修改的话必须在别的地方修改吗

**Comment by drepig** [comment]
啊我好像自己整明白了，是我自己蠢了，没有把路径啥的写对，不需要把所有文件夹都copy过去，只需要拷贝dist下的，然后二次开发就说明了，是需要重新开发组件生成代码，然后直接用的。不过这样的话会不会造成日历组件和其他组件之间的交互性不方便呢？

**Comment by lspriv** [comment]
我会考虑这个问题
