### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by pengweiqiang** [lspriv/wx-calendar#35]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/9783103/179172685-2d6f6129-21ad-491e-84c8-11a322c73b9c.png">

**Comment by pengweiqiang** [comment]
<calendar id="calendar" checkedShow="true"  showMark="false" view="week" binddatechange="dateChange" />
偶现

**Comment by pengweiqiang** [comment]
`<calendar id="calendar" checkedShow="true"  showMark="false" view="week" binddatechange="dateChange" />`
偶现

**Comment by Chadwuo** [comment]
> `<calendar id="calendar" checkedShow="true" showMark="false" view="week" binddatechange="dateChange" />` 偶现

请问，找到原因了吗

**Comment by pengweiqiang** [comment]
> 没有，换插件了

**Comment by pengweiqiang** [comment]
> > `<calendar id="calendar" checkedShow="true" showMark="false" view="week" binddatechange="dateChange" />` 偶现
> 
> 请问，找到原因了吗

没有，换插件了

**Comment by Chadwuo** [comment]
> > > `<calendar id="calendar" checkedShow="true" showMark="false" view="week" binddatechange="dateChange" />` 偶现
> > 
> > 
> > 请问，找到原因了吗
> 
> 没有，换插件了

换了什么，能丢个地址给我看一下吗

**Comment by pengweiqiang** [comment]
> > > > `<calendar id="calendar" checkedShow="true" showMark="false" view="week" binddatechange="dateChange" />` 偶现
> > > 
> > > 
> > > 请问，找到原因了吗
> > 
> > 
> > 没有，换插件了
> 
> 换了什么，能丢个地址给我看一下吗

https://github.com/treadpit/wx_calendar

**Comment by Chadwuo** [comment]
> > > > > `<calendar id="calendar" checkedShow="true" showMark="false" view="week" binddatechange="dateChange" />` 偶现
> > > > 
> > > > 
> > > > 请问，找到原因了吗
> > > 
> > > 
> > > 没有，换插件了
> > 
> > 
> > 换了什么，能丢个地址给我看一下吗
> 
> https://github.com/treadpit/wx_calendar

谢谢，你新换的这个我看到过，还是觉得讨论的这个好看点
