### ISSUE TITLE
为什么我引入之后没有任何样式？

### ISSUE THREAD

**Issue by Arlexovincy** [lspriv/wx-calendar#36]
![image](https://user-images.githubusercontent.com/4088608/233241699-0f396b67-3830-40a8-8317-82dae3c8b121.png)
![image](https://user-images.githubusercontent.com/4088608/233241722-7d971003-983c-4935-bede-41d44867903e.png)
![image](https://user-images.githubusercontent.com/4088608/233241746-32eef050-5fcc-4ebb-817e-2b98dca351ed.png)
为什么我引入之后没有任何样式呢？

**Comment by lspriv** [comment]
重构了，分支develop
