### ISSUE TITLE
农历问题

### ISSUE THREAD

**Issue by asugg** [lspriv/wx-calendar#7]
请问怎么去掉农历显示呢？

**Comment by lspriv** [comment]
这一版还没有添加控制农历显隐的属性，后面会加上

**Comment by asugg** [comment]
> 这一版本还没有添加控制农历重大隐的属性，后面会加上

markers 数据动态变化，日历显示不更新的么？

**Comment by lspriv** [comment]
在最开始的设计时是加了监听的，后面在提供了setMakers方法和bindrangechange事件中的markerCommit方法后，感觉重复设计了，就给去掉了，无论是setMakers还是markerCommit都会更新

**Comment by asugg** [comment]
> 在最开始的设计时是加了监听的，后面在提供了setMakers方法和bindrangechange事件中的markerCommit方法后，感觉重复设计了，就给去掉了，无论是setMakers还是markerCommit都会更新

如果本身有数据，然后再setMakers空数据后，本身存在的marker还会显示着，这个有什么方法解决么？

**Comment by lspriv** [comment]
这应该是个bug，我会明天修复------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月21日(星期五) 晚上6:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lspriv/wx-calendar] 农历问题 (#7)

**Comment by asugg** [comment]
> 这应该是个bug，我会明天修复------------------＆nbsp;原始邮件＆nbsp; ----------------- -***@***.***> 发送时间：＆nbsp; 2021年5月21日（星期五）晚上6:51 ***@***.***> ;; *** @ ***。****** @ ***。***＆gt ;; 主题：＆nbsp; Re：[lspriv / wx-calendar]农历问题（[＃7](https://github.com/lspriv/wx-calendar/issues/7)）

请问这个bug改好了么。。

**Comment by lspriv** [comment]
bug修复了，最近忙着离职，耽搁了
