### ISSUE TITLE
屏幕出现滚动条，全屏下选择月份，日期出错

### ISSUE THREAD

**Issue by mapleeeeeee** [lspriv/wx-calendar#79]
第一次选择2024-9月，日期响应为2024-12
第一次选择2024-12月，日期响应为2025-03
![日期](https://github.com/lspriv/wx-calendar/assets/112382489/4cd0547b-fdfd-498d-aeb0-1e03af7c8e12)

**Comment by mapleeeeeee** [comment]
![日期](https://github.com/lspriv/wx-calendar/assets/112382489/5b1f65b8-c268-4b3e-a4b7-4be282276c8d)

**Comment by lspriv** [comment]
能提供小程序库版本吗

**Comment by mapleeeeeee** [comment]
> 能提供小程序库版本吗

调试库版本：3.3.2
插件版本：1.5.1

**Comment by lspriv** [comment]
> > 能提供小程序库版本吗
> 
> 调试库版本：3.3.2 插件版本：1.5.1
出现滚动条是橙色部分撑起来的，日历组件并不是位置固定的，你想位置固定的话传style。
选择月份出错这个bug我修复一下

**Comment by lspriv** [comment]
包@lspriv/wx-calendar@1.5.2-alpha.1已修复滚动页面下的月份选择错误
