### ISSUE TITLE
周，月，计划，固定视图 和深色模式无效

### ISSUE THREAD

**Issue by mapleeeeeee** [lspriv/wx-calendar#80]
版本：1.5.1
1.view属性加上 -fixed 属性无效
2.深色模式无效

代码如下
![image](https://github.com/lspriv/wx-calendar/assets/112382489/aed2645a-c6de-4bab-86d0-469081b8137b)

<view>
  <view style="height:10vh;"></view>

  <calendar id="calendar" vibrate='{{false}}' 
  view="week-fixed" 
  darkmode="{{true}}" />

</view>

**Comment by lspriv** [comment]
1.组件为了适配 skyline，小程序库版本在 3.0.0 以上
<img width="464" alt="截屏2024-01-18 16 33 24" src="https://github.com/lspriv/wx-calendar/assets/45302341/eb53c710-6683-495c-a10c-f565f1cce731">
2.深色模式，响应微信的模式改变，要在 app.json中配置 darkmode: true; 微信变深色模式后就会改变。

**Comment by lspriv** [comment]
> 版本：1.5.1 1.view属性加上 -fixed 属性无效 2.深色模式无效
> 
> 代码如下 ![image](https://private-user-images.githubusercontent.com/112382489/297674342-aed2645a-c6de-4bab-86d0-469081b8137b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Njg0OTAsIm5iZiI6MTcwNTU2ODE5MCwicGF0aCI6Ii8xMTIzODI0ODkvMjk3Njc0MzQyLWFlZDI2NDVhLWM2ZGUtNGJhYi04NmQwLTQ2OTA4MWI4MTM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwODU2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmVhY2NmMmU0ZTQ1MTQyZDJiNjNiZWEzZmE2NDgxMDAwMTQzYzIwYWQzZjY0N2VlNWI0YWVhYTVhZGE0NmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UFGsdULAbZplV3szsgilFB4GvphLAW8LQYq2KvdE2iE)

根据你提供的代码和版本，测试了固定视图，week-fixed没有问题

**Comment by mapleeeeeee** [comment]
小程序版本为：3.3.2
我重新截了个图，日期无法固定
![日期固定](https://github.com/lspriv/wx-calendar/assets/112382489/5ae0880f-a615-4e5b-a02a-4ecc9eadc8b1)

**Comment by lspriv** [comment]
> 小程序版本为：3.3.2 我重新截了个图，日期无法固定 ![日期固定](https://private-user-images.githubusercontent.com/112382489/297683862-5ae0880f-a615-4e5b-a02a-4ecc9eadc8b1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjkzNDgsIm5iZiI6MTcwNTU2OTA0OCwicGF0aCI6Ii8xMTIzODI0ODkvMjk3NjgzODYyLTVhZTA4ODBmLWE2MTUtNGU1Yi1hMDJhLTRlY2M5ZWFkYzhiMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwOTEwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjZiMGE3MTU1OTljMDBkN2ZiNTFkYzEzYjUzZTgzMDQ1NzlhNmZlMTNjNDgyMzljZTg1YTc1NzQ2ZjdmZjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OY2uK55kxyBjTWPR1kwqloyd1-nQmBtTtQgAhfnAgZs) [ ![日期固定](https://private-user-images.githubusercontent.com/112382489/297683862-5ae0880f-a615-4e5b-a02a-4ecc9eadc8b1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjkzNDgsIm5iZiI6MTcwNTU2OTA0OCwicGF0aCI6Ii8xMTIzODI0ODkvMjk3NjgzODYyLTVhZTA4ODBmLWE2MTUtNGU1Yi1hMDJhLTRlY2M5ZWFkYzhiMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwOTEwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjZiMGE3MTU1OTljMDBkN2ZiNTFkYzEzYjUzZTgzMDQ1NzlhNmZlMTNjNDgyMzljZTg1YTc1NzQ2ZjdmZjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OY2uK55kxyBjTWPR1kwqloyd1-nQmBtTtQgAhfnAgZs) ](https://private-user-images.githubusercontent.com/112382489/297683862-5ae0880f-a615-4e5b-a02a-4ecc9eadc8b1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjkzNDgsIm5iZiI6MTcwNTU2OTA0OCwicGF0aCI6Ii8xMTIzODI0ODkvMjk3NjgzODYyLTVhZTA4ODBmLWE2MTUtNGU1Yi1hMDJhLTRlY2M5ZWFkYzhiMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwOTEwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjZiMGE3MTU1OTljMDBkN2ZiNTFkYzEzYjUzZTgzMDQ1NzlhNmZlMTNjNDgyMzljZTg1YTc1NzQ2ZjdmZjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OY2uK55kxyBjTWPR1kwqloyd1-nQmBtTtQgAhfnAgZs) [ ](https://private-user-images.githubusercontent.com/112382489/297683862-5ae0880f-a615-4e5b-a02a-4ecc9eadc8b1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjkzNDgsIm5iZiI6MTcwNTU2OTA0OCwicGF0aCI6Ii8xMTIzODI0ODkvMjk3NjgzODYyLTVhZTA4ODBmLWE2MTUtNGU1Yi1hMDJhLTRlY2M5ZWFkYzhiMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwOTEwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjZiMGE3MTU1OTljMDBkN2ZiNTFkYzEzYjUzZTgzMDQ1NzlhNmZlMTNjNDgyMzljZTg1YTc1NzQ2ZjdmZjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OY2uK55kxyBjTWPR1kwqloyd1-nQmBtTtQgAhfnAgZs)

我还是没有复现你这个bug
![Uploading 截屏2024-01-18 17.16.16.png…]()

**Comment by lspriv** [comment]
> 小程序版本为：3.3.2 我重新截了个图，日期无法固定 ![日期固定](https://private-user-images.githubusercontent.com/112382489/297683862-5ae0880f-a615-4e5b-a02a-4ecc9eadc8b1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjkzNDgsIm5iZiI6MTcwNTU2OTA0OCwicGF0aCI6Ii8xMTIzODI0ODkvMjk3NjgzODYyLTVhZTA4ODBmLWE2MTUtNGU1Yi1hMDJhLTRlY2M5ZWFkYzhiMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwOTEwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjZiMGE3MTU1OTljMDBkN2ZiNTFkYzEzYjUzZTgzMDQ1NzlhNmZlMTNjNDgyMzljZTg1YTc1NzQ2ZjdmZjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OY2uK55kxyBjTWPR1kwqloyd1-nQmBtTtQgAhfnAgZs) 

我还没有复现 :disappointed:
![截屏2024-01-18 17 16 16](https://github.com/lspriv/wx-calendar/assets/45302341/9d351c91-b70f-45c4-83df-f5bc4c884a49)

**Comment by mapleeeeeee** [comment]
发现问题了，是缓存的原因
我是从1.0.0版本升到1.5.1，加上fixed无效，
新建了一个项目装上1.5.1就没有这个问题。
谢谢大佬。
