### ISSUE TITLE
被选中的 （节气，节假日）的字体颜色不是 --wc-checked-mark-color 的颜色

### ISSUE THREAD

**Issue by Coffee-rabbit** [lspriv/wx-calendar#89]
![20240202155246](https://github.com/lspriv/wx-calendar/assets/55985870/a9e66151-384a-4515-8ee1-03cf2e41f098)

**Comment by lspriv** [comment]
收到

**Comment by lspriv** [comment]
节气节假日的颜色特别于普通日期的，建议将 --wc-solar-color 并调整

**Comment by lspriv** [comment]
自定义的mark颜色覆盖了被选中后的默认颜色，自定义的颜色优先级最高，这个问题在于选中圆圈设置的背景色和选中时mark颜色区分不明显在 2024年2月2日，15:53，Coffee-rabbit ***@***.***> 写道：﻿
QQ.20240119103344.jpg (view on web)

**Comment by lspriv** [comment]
包@lspriv/wx-calendar@1.5.5-alpha.0已调整解决这个问题。
新增属性sameChecked以控制选中日期样式一致
```html
<calendar sameChecked="{{ true }}" style="--wc-checked-bg: #409EFF;" />
```
